[project]
name = "snakemake tutorial"
version = "0.1.0"
description = "A template for installing and running a snakemake workflow with pixi."
authors = ["Sibbe Bakker <sibbe.l.bakker@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "win-64"]


[tasks]
make = "snakemake --use-conda -c 1"
test = "snakemake --use-conda -c 1 -np"
# Linux only
slurm = "snakemake --use-conda --workflow-profile workflow/profiles/slurm"
help  = "bash workflow/help.sh"
make-help  = "sed -n 's/^##//p' workflow/Snakefile"
make-dag = "mkdir resources; snakemake --use-conda --quiet all -c 1 'results/method.png' && mv results/method.png resources; mv resources/method.png resources/pipeline.png"


[dependencies]
curl = ">=8.7.1,<8.8"
snakemake = ">=8.10.8,<8.11"
mamba = ">=1.5.8,<1.6"
# tree = ">=2.1.1,<2.2"
# snakemake-executor-plugin-slurm = ">=0.6.0,<0.7"
# sed = ">=4.8,<5"
# gzip = ">=1.13,<2"
# tar = ">=1.34,<2"

[system-requirements]
linux="4.12.14"
